version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    links:
      - mongodb:mongodb 
  mongodb:
    image: 'bitnami/mongodb:3.6'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
